run:
  timeout: 5m

linters:
  enable:
    - deadcode
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - structcheck
    - typecheck
    - unused
    - varcheck
    - gocyclo
    - gofmt
    - goimports
    - golint
    - misspell
    - unconvert
    - goconst
    - gocritic

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
